export const ENGLISH_RESOURCES = {
  'common.productName': 'StudyWeave',
  'common.productDescription': 'One place for your questions, practice, and learning journey.',
  'common.errors.internal': 'Something went wrong. Please try again later.',
  'common.errors.notFound': 'The requested resource was not found.',
  'form.actions.hidePassword': 'Hide password',
  'form.actions.showPassword': 'Show password',
  'auth.errors.invalidCredentials': 'The username or password is incorrect.',
  'auth.errors.invalidResponse': 'The server returned an invalid response.',
  'auth.errors.requestFailed': 'The request could not be completed. Please try again.',
  'auth.errors.usernameTaken': 'That username is already in use.',
  'login.description': 'Enter your account details to continue to your learning space.',
  'login.fields.password': 'Password',
  'login.fields.username': 'Username',
  'login.heading': 'Sign in',
  'login.links.noAccount': 'New to StudyWeave?',
  'login.links.register': 'Create an account',
  'login.status.submitting': 'Signing in…',
  'login.status.success': 'You are signed in.',
  'login.submit': 'Sign in',
  'notFound.action': 'Back to sign in',
  'notFound.description': 'The address does not exist, or the page has moved somewhere else.',
  'notFound.heading': 'Page not found',
  'notFound.links.login': 'Go to the sign-in page',
  'register.description': 'Choose a username and password to start learning with StudyWeave.',
  'register.fields.displayName': 'Display name',
  'register.fields.password': 'Password',
  'register.fields.username': 'Username',
  'register.heading': 'Create an account',
  'register.links.hasAccount': 'Already have an account?',
  'register.links.login': 'Sign in',
  'register.status.submitting': 'Creating your account…',
  'register.status.success': 'Your account was created.',
  'register.submit': 'Register',
  'validation.errors.displayNameLength':
    'The display name must contain no more than 100 characters.',
  'validation.errors.displayNameRequired': 'Enter a display name.',
  'validation.errors.invalidBody': 'The submitted details are invalid.',
  'validation.errors.passwordLength': 'The password must contain 8 to 128 characters.',
  'validation.errors.passwordRequired': 'Enter a password.',
  'validation.errors.usernameInvalid':
    'The username must contain 3 to 50 letters, numbers, dots, underscores, or hyphens.',
  'validation.errors.usernameRequired': 'Enter a username.',
} as const;

/**
 * Stable semantic key available in every supported resource dictionary.
 *
 * @example
 * const key: ResourceKey = 'login.heading';
 */
export type ResourceKey = keyof typeof ENGLISH_RESOURCES;

export const HEBREW_RESOURCES: Readonly<Record<ResourceKey, string>> = {
  'common.productName': 'מכלול',
  'common.productDescription': 'מרחב אחד לכל השאלות, התרגולים ותהליכי הלמידה שלך.',
  'common.errors.internal': 'אירעה שגיאה פנימית. נסו שוב מאוחר יותר.',
  'common.errors.notFound': 'המשאב המבוקש לא נמצא.',
  'form.actions.hidePassword': 'הסתרת הסיסמה',
  'form.actions.showPassword': 'הצגת הסיסמה',
  'auth.errors.invalidCredentials': 'שם המשתמש או הסיסמה שגויים.',
  'auth.errors.invalidResponse': 'התקבלה תשובה לא תקינה מהשרת.',
  'auth.errors.requestFailed': 'לא ניתן להשלים את הפעולה. נסו שוב.',
  'auth.errors.usernameTaken': 'שם המשתמש כבר נמצא בשימוש.',
  'login.description': 'הזינו את פרטי החשבון כדי להמשיך למרחב הלמידה.',
  'login.fields.password': 'סיסמה',
  'login.fields.username': 'שם משתמש',
  'login.heading': 'התחברות',
  'login.links.noAccount': 'עדיין אין לך חשבון?',
  'login.links.register': 'יצירת חשבון',
  'login.status.submitting': 'מתחברים…',
  'login.status.success': 'ההתחברות הושלמה בהצלחה.',
  'login.submit': 'התחברות',
  'notFound.action': 'חזרה להתחברות',
  'notFound.description': 'הכתובת שביקשת אינה קיימת או שהעמוד הועבר למקום אחר.',
  'notFound.heading': 'העמוד לא נמצא',
  'notFound.links.login': 'מעבר לעמוד ההתחברות',
  'register.description': 'בחרו שם משתמש וסיסמה כדי להתחיל ללמוד במכלול.',
  'register.fields.displayName': 'שם תצוגה',
  'register.fields.password': 'סיסמה',
  'register.fields.username': 'שם משתמש',
  'register.heading': 'יצירת חשבון',
  'register.links.hasAccount': 'כבר יש לך חשבון?',
  'register.links.login': 'להתחברות',
  'register.status.submitting': 'יוצרים חשבון…',
  'register.status.success': 'החשבון נוצר בהצלחה.',
  'register.submit': 'הרשמה',
  'validation.errors.displayNameLength': 'שם התצוגה חייב להכיל עד 100 תווים.',
  'validation.errors.displayNameRequired': 'יש להזין שם תצוגה.',
  'validation.errors.invalidBody': 'הנתונים שנשלחו אינם תקינים.',
  'validation.errors.passwordLength': 'הסיסמה חייבת להכיל בין 8 ל־128 תווים.',
  'validation.errors.passwordRequired': 'יש להזין סיסמה.',
  'validation.errors.usernameInvalid':
    'שם המשתמש חייב להכיל 3 עד 50 תווים: אותיות, ספרות, נקודות, קווים תחתונים או מקפים בלבד.',
  'validation.errors.usernameRequired': 'יש להזין שם משתמש.',
};
