export const ENGLISH_RESOURCES = {
  'auth.errors.authenticationRequired': 'Sign in to ask and view questions.',
  'questions.actions.send': 'Send',
  'questions.actions.sending': 'Sending…',
  'questions.actions.stop': 'Stop',
  'questions.actions.stopping': 'Stopping…',
  'questions.answerHeading': 'Answer',
  'questions.description':
    'Write a question and follow its progress while the AI prepares an answer.',
  'questions.errors.answerFailed': 'The AI could not answer this question. Please try again.',
  'questions.errors.cancellationFailed': 'The stop request could not be sent. Please try again.',
  'questions.errors.dispatchFailed': 'The question could not be queued. Please try again.',
  'questions.errors.invalidResponse': 'The server returned an invalid question response.',
  'questions.errors.notFound': 'This question was not found.',
  'questions.errors.rateLimitExceeded':
    'Too many questions were sent in a short time. Please wait and try again.',
  'questions.errors.requestFailed':
    'The question request could not be completed. Please try again.',
  'questions.fields.placeholder': 'Type your question here…',
  'questions.fields.question': 'Question',
  'questions.heading': 'Ask StudyWeave',
  'questions.status.cancelled': 'The request was stopped.',
  'questions.status.cancellationRequested': 'Stopping the request…',
  'questions.status.completed': 'The answer is ready.',
  'questions.status.failed': 'The request failed.',
  'questions.status.processing': 'Preparing an answer…',
  'questions.status.queued': 'Waiting for a worker…',
  'validation.errors.questionLength': 'The question must contain no more than 20,000 characters.',
  'validation.errors.questionRequired': 'Enter a question.',
  'common.productName': 'StudyWeave',
  'common.productDescription': 'One place for your questions, practice, and learning journey.',
  'common.errors.internal': 'Something went wrong. Please try again later.',
  'common.errors.notFound': 'The requested resource was not found.',
  'form.actions.hidePassword': 'Hide password',
  'form.actions.showPassword': 'Show password',
  'auth.errors.invalidCredentials': 'The username or password is incorrect.',
  'auth.errors.invalidResponse': 'The server returned an invalid response.',
  'auth.errors.requestFailed': 'The request could not be completed. Please try again.',
  'auth.errors.usernameTaken': 'That username is already in use.',
  'login.description': 'Enter your account details to continue to your learning space.',
  'login.fields.password': 'Password',
  'login.fields.username': 'Username',
  'login.heading': 'Sign in',
  'login.links.noAccount': 'New to StudyWeave?',
  'login.links.register': 'Create an account',
  'login.status.submitting': 'Signing in…',
  'login.status.success': 'You are signed in.',
  'login.submit': 'Sign in',
  'register.description': 'Choose a username and password to start learning with StudyWeave.',
  'register.fields.displayName': 'Display name',
  'register.fields.password': 'Password',
  'register.fields.username': 'Username',
  'register.heading': 'Create an account',
  'register.links.hasAccount': 'Already have an account?',
  'register.links.login': 'Sign in',
  'register.status.submitting': 'Creating your account…',
  'register.status.success': 'Your account was created.',
  'register.submit': 'Register',
  'validation.errors.displayNameLength':
    'The display name must contain no more than 100 characters.',
  'validation.errors.displayNameRequired': 'Enter a display name.',
  'validation.errors.invalidBody': 'The submitted details are invalid.',
  'validation.errors.passwordLength': 'The password must contain 8 to 128 characters.',
  'validation.errors.passwordRequired': 'Enter a password.',
  'validation.errors.usernameInvalid':
    'The username must contain 3 to 50 letters, numbers, dots, underscores, or hyphens.',
  'validation.errors.usernameRequired': 'Enter a username.',
} as const;

/**
 * Stable semantic key available in every supported resource dictionary.
 *
 * @example
 * const key: ResourceKey = 'login.heading';
 */
export type ResourceKey = keyof typeof ENGLISH_RESOURCES;

export const HEBREW_RESOURCES: Readonly<Record<ResourceKey, string>> = {
  'auth.errors.authenticationRequired': 'יש להתחבר כדי לשאול שאלות ולצפות בהן.',
  'questions.actions.send': 'שליחה',
  'questions.actions.sending': 'שולחים…',
  'questions.actions.stop': 'עצירה',
  'questions.actions.stopping': 'עוצרים…',
  'questions.answerHeading': 'תשובה',
  'questions.description': 'כתבו שאלה ועקבו אחר ההתקדמות בזמן שהבינה המלאכותית מכינה תשובה.',
  'questions.errors.answerFailed': 'לא הצלחנו לענות על השאלה. אפשר לנסות שוב.',
  'questions.errors.cancellationFailed': 'לא הצלחנו לשלוח את בקשת העצירה. אפשר לנסות שוב.',
  'questions.errors.dispatchFailed': 'לא הצלחנו להעביר את השאלה לתור. אפשר לנסות שוב.',
  'questions.errors.invalidResponse': 'השרת החזיר תשובת שאלה לא תקינה.',
  'questions.errors.notFound': 'השאלה לא נמצאה.',
  'questions.errors.rateLimitExceeded': 'נשלחו יותר מדי שאלות בזמן קצר. המתינו מעט ונסו שוב.',
  'questions.errors.requestFailed': 'לא הצלחנו להשלים את בקשת השאלה. אפשר לנסות שוב.',
  'questions.fields.placeholder': 'כתבו כאן את השאלה שלכם…',
  'questions.fields.question': 'שאלה',
  'questions.heading': 'שואלים את StudyWeave',
  'questions.status.cancelled': 'הבקשה נעצרה.',
  'questions.status.cancellationRequested': 'עוצרים את הבקשה…',
  'questions.status.completed': 'התשובה מוכנה.',
  'questions.status.failed': 'הבקשה נכשלה.',
  'questions.status.processing': 'מכינים תשובה…',
  'questions.status.queued': 'ממתינים לעיבוד…',
  'validation.errors.questionLength': 'השאלה יכולה להכיל עד 20,000 תווים.',
  'validation.errors.questionRequired': 'יש להזין שאלה.',
  'common.productName': 'מכלול',
  'common.productDescription': 'מרחב אחד לכל השאלות, התרגולים ותהליכי הלמידה שלך.',
  'common.errors.internal': 'אירעה שגיאה פנימית. נסו שוב מאוחר יותר.',
  'common.errors.notFound': 'המשאב המבוקש לא נמצא.',
  'form.actions.hidePassword': 'הסתרת הסיסמה',
  'form.actions.showPassword': 'הצגת הסיסמה',
  'auth.errors.invalidCredentials': 'שם המשתמש או הסיסמה שגויים.',
  'auth.errors.invalidResponse': 'התקבלה תשובה לא תקינה מהשרת.',
  'auth.errors.requestFailed': 'לא ניתן להשלים את הפעולה. נסו שוב.',
  'auth.errors.usernameTaken': 'שם המשתמש כבר נמצא בשימוש.',
  'login.description': 'הזינו את פרטי החשבון כדי להמשיך למרחב הלמידה.',
  'login.fields.password': 'סיסמה',
  'login.fields.username': 'שם משתמש',
  'login.heading': 'התחברות',
  'login.links.noAccount': 'עדיין אין לך חשבון?',
  'login.links.register': 'יצירת חשבון',
  'login.status.submitting': 'מתחברים…',
  'login.status.success': 'ההתחברות הושלמה בהצלחה.',
  'login.submit': 'התחברות',
  'register.description': 'בחרו שם משתמש וסיסמה כדי להתחיל ללמוד במכלול.',
  'register.fields.displayName': 'שם תצוגה',
  'register.fields.password': 'סיסמה',
  'register.fields.username': 'שם משתמש',
  'register.heading': 'יצירת חשבון',
  'register.links.hasAccount': 'כבר יש לך חשבון?',
  'register.links.login': 'להתחברות',
  'register.status.submitting': 'יוצרים חשבון…',
  'register.status.success': 'החשבון נוצר בהצלחה.',
  'register.submit': 'הרשמה',
  'validation.errors.displayNameLength': 'שם התצוגה חייב להכיל עד 100 תווים.',
  'validation.errors.displayNameRequired': 'יש להזין שם תצוגה.',
  'validation.errors.invalidBody': 'הנתונים שנשלחו אינם תקינים.',
  'validation.errors.passwordLength': 'הסיסמה חייבת להכיל בין 8 ל־128 תווים.',
  'validation.errors.passwordRequired': 'יש להזין סיסמה.',
  'validation.errors.usernameInvalid':
    'שם המשתמש חייב להכיל 3 עד 50 תווים: אותיות, ספרות, נקודות, קווים תחתונים או מקפים בלבד.',
  'validation.errors.usernameRequired': 'יש להזין שם משתמש.',
};
